# Generated by Django 5.1.3 on 2025-01-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basecitypage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('city_image', models.ImageField(upload_to='cityimages/')),
                ('city_description', models.TextField()),
                ('city_gallery1', models.ImageField(upload_to='cityimages/')),
                ('city_gallery2', models.ImageField(upload_to='cityimages/')),
                ('city_gallery3', models.ImageField(upload_to='cityimages/')),
                ('city_gallery4', models.ImageField(upload_to='cityimages/')),
                ('city_gallery5', models.ImageField(upload_to='cityimages/')),
                ('city_map', models.ImageField(upload_to='cityimages/')),
            ],
        ),
    ]
