# Generated by Django 5.1.3 on 2025-01-31 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_basecitypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='app1.basecitypage'),
        ),
    ]
