# Generated by Django 5.1.3 on 2025-02-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_package_details_category_package_details_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package_details_sub',
            name='pid',
        ),
        migrations.DeleteModel(
            name='package_details_category',
        ),
        migrations.DeleteModel(
            name='package_details_sub',
        ),
    ]
