# Generated by Django 5.1.3 on 2025-02-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_package_details_sub_t1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_details_sub',
            name='t1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='package_details_sub',
            name='t2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='package_details_sub',
            name='t3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='package_details_sub',
            name='t4',
            field=models.TextField(),
        ),
    ]
