# Generated by Django 5.1.3 on 2025-01-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_packages_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecitypage',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
