# Generated by Django 5.1.3 on 2025-01-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_basecitypage_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecitypage',
            name='slug',
        ),
        migrations.AlterField(
            model_name='packages',
            name='Availability',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
