# Generated by Django 5.1.3 on 2025-02-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_package_details_sub_pid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='signinModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=45, null=True)),
            ],
        ),
    ]
