# Generated by Django 5.1.3 on 2025-02-10 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_package_details_category_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package_details_category',
            name='package',
        ),
        migrations.RemoveField(
            model_name='package_details_category',
            name='package_details',
        ),
    ]
