# Generated by Django 5.1.3 on 2025-02-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_contact_package_contact_submitted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package_details',
            name='video2',
        ),
        migrations.RemoveField(
            model_name='package_details',
            name='video3',
        ),
        migrations.AlterField(
            model_name='package_details',
            name='video1',
            field=models.FileField(blank=True, null=True, upload_to='cityvideo/'),
        ),
    ]
