# Generated by Django 5.1.3 on 2025-02-21 07:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_alter_basecitypage_city_gallery1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_details',
            name='video1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
    ]
