# Generated by Django 5.1.3 on 2025-01-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_image', models.ImageField(upload_to='images/')),
                ('package_name', models.CharField(max_length=50)),
                ('discount_price', models.IntegerField()),
                ('full_price', models.IntegerField()),
                ('Availability', models.CharField(max_length=25)),
                ('no_of_days', models.CharField(max_length=25)),
            ],
        ),
    ]
