# Generated by Django 5.1.3 on 2025-02-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_basecitypage_slug_alter_packages_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityheading', models.CharField(max_length=50)),
                ('city_sub_desc', models.CharField(max_length=100)),
                ('video1', models.ImageField(upload_to='cityvideos/')),
                ('video2', models.ImageField(upload_to='cityvideos/')),
                ('video3', models.ImageField(upload_to='cityvideos/')),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=200)),
                ('temperature1', models.CharField(max_length=30)),
                ('temperature2', models.CharField(max_length=30)),
                ('eventcost', models.IntegerField()),
                ('flashsaleprice', models.IntegerField()),
                ('couplesharingcost', models.IntegerField()),
                ('place1heading', models.CharField(max_length=100)),
                ('place1description', models.TextField()),
                ('place2heading', models.CharField(max_length=100)),
                ('place2description', models.TextField()),
                ('place3heading', models.CharField(max_length=100)),
                ('place3description', models.TextField()),
                ('place4heading', models.CharField(max_length=100)),
                ('place4description', models.TextField()),
                ('staysheading', models.CharField(max_length=200)),
                ('staysdescription', models.TextField()),
                ('totalcost', models.IntegerField()),
                ('meetingpointcity', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to='customerimages/')),
                ('image2', models.ImageField(upload_to='customerimages/')),
                ('image3', models.ImageField(upload_to='customerimages/')),
                ('image4', models.ImageField(upload_to='customerimages/')),
                ('image5', models.ImageField(upload_to='customerimages/')),
            ],
        ),
    ]
