# Generated by Django 5.1.3 on 2025-02-04 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_package_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_details',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='customerimages/'),
        ),
        migrations.AddField(
            model_name='package_details',
            name='package',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app1.packages'),
        ),
    ]
