# Generated by Django 5.1.3 on 2025-02-10 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_package_details_category_package_details_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_details_category',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details_category', to='app1.packages'),
        ),
        migrations.AddField(
            model_name='package_details_category',
            name='package_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app1.package_details'),
        ),
    ]
