# Generated by Django 5.1.3 on 2025-02-10 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_remove_package_details_category_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_details_category',
            name='package_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.packages'),
        ),
    ]
