# Generated by Django 5.1.3 on 2025-02-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_package_details_category_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_details_sub',
            name='t1',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='package_details_sub',
            name='t2',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='package_details_sub',
            name='t3',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='package_details_sub',
            name='t4',
            field=models.CharField(max_length=1000),
        ),
    ]
